module.exports.data = [
  "Yanki Sizzlers",
  "TG’s - The Oriental Grill - Hyatt",
  "Echoes Ahmedabad",
  "Mocha",
  "Soulmate - Make Moments Memorable",
  "Urban Khichdi",
  "Kovallam",
  "Tomato's",
  "Sale and Pepe",
  "Barbeque Nation",
  "Sante Spa Cuisine",
  "Ph Se Food",
  "Jassi De Parathe",
  "The Red Bistro",
  "Gordhan Thaal",
  "Nini's Kitchen",
  "The Grand Thakar",
  "Makeba - The Lounge Cafe",
  "RP's Pizzeria",
  "@Mango",
  "Brick Kitchen - Five Petals",
  "Vishalla",
  "Dakshinayan",
  "Stuff's Food",
  "M.A.D By Tomato's",
  "Rajwadu",
  "SandwichworkZ - The Fusion Street Cafe",
  "Dhoom Dhaam",
  "Nanjing",
  "Fayrouz",
  "MIY Bistro - Make It Yourself",
  "Gwalia Vanakkam",
  "Just Food Inn",
  "Buddy - The Family Restaurant",
  "Temptt Restro And Cafe",
  "New York Slice",
  "Daawat-E-Khaas",
  "The Blue Oven",
  "Ristretto - Behind the Rods",
  "1944 Restaurant By Havmor",
  "Khichdi Etc",
  "Poetry",
  "650 - The Global Kitchen",
  "Masala Canteen",
  "Kaffee - Mast Hai",
  "Cafe Upper Crust",
  "Capsicum",
  "The Egg Eatery - Eggstremely Delicious",
  "The Trophy by Tomato's",
  "Fresh Roast - Mani Mansion",
  "Eleven 11 Restro Cafe",
  "Dhabagiri",
  "Unique Eats Restro Cafe",
  "Amicorum",
  "AB's - Absolute Barbecue",
  "Simply Meaty",
  "South Leaf- The Food Chain",
  "Bogarosa",
  "The Secret Kitchen",
  "Eleven 11 Restro Cafe",
  "Havmor Restaurant",
  "Yash's GBT",
  "Rasila's Kitchen",
  "70 Degrees East",
  "Curries",
  "Mirch Masala",
  "Terracotta",
  "Juggernaut",
  "Little Italy",
  "Cafe Upper Crust",
  "Aureate - El Dorado",
  "Massala Theoryy",
  "From The North",
  "Bollywood Lounge",
  "Maruti Dining Hall",
  "R Kitchen - Renaissance Hotel",
  "So Hi Kebabs & Curries Company",
  "Hashtag",
  "Akshada",
  "Jashn",
  "Swaad Sadan",
  "Tangled",
  "Kuro - Renaissance Hotel",
  "South 54",
  "TGIH - Thank God It's Healthy",
  "Vanashree",
  "Karma Cafe",
  "Falashin Juices & Dishes",
  "Kabir Restaurant",
  "Upri Manzil",
  "Parosa",
  "Lollo Rosso",
  "Swati Snacks",
  "Lollo Rosso",
  "Huber & Holly",
  "Lijjat Khaman",
  "Harry's Kitchen",
  "Magic Chicken",
  "La Pino'z Pizza",
  "Falashin Juices & Dishes",
  "Urban Khichdi",
  "Balan Dosa",
  "Mahaveer Food Point",
  "Burgerlicious",
  "Das Khaman",
  "Khichdi Etc",
  "Ambika Dalvada Centre",
  "Karnawati Dabeli Centre",
  "New Famous Samosa House",
  "Food Station",
  "Shri Jay Jalaram Khaman House",
  "Rp's Pizzeria",
  "Puffizza",
  "Royal Punjab Paratha",
  "Shreejikrupa",
  "Manek Sandwich & Pizza",
  "Bhookh Lagi Hai",
  "Gajanand Food",
  "Matka Khichdi",
  "Udupi Shree Darshini Restaurant",
  "Kosho's Sauces and Sausages",
  "Bhookh Lagi Hai",
  "New Freeze Land",
  "Melt In",
  "Apna Punjab Parattha",
  "M.L.F Franco",
  "Kesar Foods",
  "Juno's Pizza",
  "Upsouth",
  "Cravenzaa",
  "Oshwal",
  "Choice Snack Bar",
  "Appetize The Bistro",
  "Icekraft",
  "Kurtosshhh",
  "Busker's Corner",
  "Jay Shree Sandwich Centre",
  "Hardy's Cafe",
  "Ambica Dalvada and Khiru",
  "Shree Manmohan Kharek Centre",
  "Arpit",
  "Hunnybun",
  "Shakti - The Sandwich Shop",
  "McDonald's",
  "Brown Burger Co",
  "Birmies",
  "New Freeze Land",
  "Taste Of Mumbai - Bombay Street Cafe",
  "Choice Snack Bar",
  "Iscon Gathiya",
  "Le Artisan Boulangerie",
  "Royal Restaurant & Banquet",
  "Theokaphe",
  "Happy Rolls",
  "Mahalaxmi Pav Bhaji",
  "Jashuben Shah Old Pizza",
  "Anand",
  "Vibrant Cafe & Food Court",
  "Joules",
  "Chai Wai",
  "New Lucky Restaurant",
  "Chef's Pizza",
  "Annam",
  "Sasuma",
  "Desi Stuff",
  "Pooja Parlour",
  "Indore Chat House",
  "Big Bite Fast Food",
  "‘Rotlo’ The Dining Hall",
  "Devarsh",
  "Foodie's Call",
  "Moti Bakery",
  "Gwalia Sweets",
  "Shree Ambika Dalvada Centre",
  "Chandra Villas",
  "The Tasty Hub",
  "Shreejikrupa",
  "Jani Locho & Khaman House",
  "Hoglatto",
  "Biskut",
  "Moi - The Dessert Studio",
  "Cocoa Drama",
  "It's A Cake Day",
  "Golden Brown",
  "All The Perks Espresso Cafe",
  "Cake My Day",
  "Upper Crust",
  "Xocolat Chocolatiers Cafe & Bakery",
  "Bakers & Cook - By Gwalia",
  "Live Cake Company",
  "Vanilla The Cake Shop",
  "Dangee Dums",
  "Mr. Puff",
  "Bakesters",
  "Brown & Happy",
  "Vanilla The Bakery And Cafe",
  "Rajkamal Bakery",
  "The Chocolate Room",
  "Gwalia Baklawa",
  "Fresh n Fresh",
  "Cake Culture",
  "Moti Bakery",
  "Baker's Den",
  "Laxmi Bakery",
  "TGB Cafe n Bakery",
  "The Home Cake Studio",
  "House of Cakes",
  "Dangee Dums",
  "Bharat Krishna Cake & Pastry",
  "Tomato's Cake Shop",
  "Choc-o-Den",
  "Beekay Bakers",
  "The Bake House By Ummed",
  "Rehamati Bakery",
  "Kabhi B",
  "Pastry 'N' Tasty",
  "Bharat Krishna Bakery",
  "Oven Magick",
  "Cupcake Corner",
  "La Patisserie",
  "Mongini's",
  "Cakes N Bakes",
  "Italian Bakery",
  "Dangee Dums Yums",
  "Deli @ The Square - Hotel Novotel",
  "Cream N Crunch",
  "Berry The Cafe And Cake",
  "DP Cake Studio",
  "Bake Me Away",
  "Chef Aarti Tejwani",
  "Shree Swaminarayan Bakery",
  "The Cake Place - Radisson Blu",
  "Fortune Cookies - Fortune Landmark",
  "Gulshan Bakery & Sweets",
  "Rich Bites Cake & Snacks",
  "Saanjh Baker's Cakes & Cafe",
  "Cafe De Macaron",
  "Roastery Cultur - The Coffee Company",
  "Mleko",
  "The Esplendido Cafe",
  "Starbucks Coffee",
  "Brewgarten",
  "Cafe De Italiano",
  "Little French House",
  "Indulgence",
  "La Patron Cafe",
  "Unlocked",
  "Gamysticafe",
  "Good Thymes",
  "Wagh Bakri Tea Lounge",
  "Danny's Coffee Bar",
  "Loft",
  "Fozzie's Pizzaiolo. Cafe. Deli",
  "Coffee Culture",
  "Queso Y Cafe",
  "I Love Sandwich House",
  "The Mad House Café",
  "Tea Villa Cafe",
  "VarieTea",
  "Sphere Lounge - Hotel Ramada",
  "VarieTea",
  "Zen Cafe",
  "Khetlaapa Cafe",
  "Basil Cafe And Bistro",
  "Amnesia - Aarya Grand",
  "Cafe Skryf",
  "The Cafe Gusto Restaurant",
  "Swat Coffee",
  "Java+ - Courtyard By Marriott",
  "And Me Cafe",
  "Cafe Piano - The Grand Bhagwati",
  "The Chocolate Room",
  "Caffix - The Tech Cafe",
  "Wagh Bakri Tea Lounge",
  "Cafe Soul Square",
  "The Dark Roast",
  "Forking Awesome",
  "Creamoholic Cafe & Restaurant",
  "Chai Shop - Hyatt Regency",
  "Terra",
  "Instaa Fresh",
  "Cafe Chocoaddict",
  "Zen Cafe",
  "The Cafe Baraco",
  "Cuppuccino",
  "Appiitto9 Cafe",
  "Beans & Leaves - Platinum Hotels",
  "Cafe Tilla",
  "The Chocolate Room",
  "Mexicano By The Bay",
  "Little Place",
  "The Chocolate Heaven",
  "Mill & Co. - Renaissance Hotel",
  "Grace Cafe",
  "Toritos Cafe Time",
  "Vince Cafe",
  "Springold The Luxury Cafe",
  "Cafe Espro",
  "Hardy's Cafe",
  "The Chocolate Room",
  "New Freeze Land",
  "85 Degrees C",
  "Moca Cabana",
  "Yuva Tantra",
  "Cafe City Monk",
  "Blue Bottle Cafe",
  "Aroma - Crowne Plaza",
  "HOP - Double Tree By Hilton",
  "Shambhu's Coffee Bar",
  "Hellish",
  "Sphere Lounge",
  "Awara The Cafe",
  "Shambhu's Coffee Bar",
  "The Costa Rica Cafe",
  "Tea Culture",
  "Levels Cafe",
  "Lil' Heaven Cafe",
  "Dravida - The Fern",
  "Agashiye - The House Of MG",
  "China House - Hyatt Regency",
  "Tinello - Hyatt Regency",
  "Mrs Mage",
  "Bayleaf - Courtyard By Marriott",
  "The Garden Cafe - The Fern",
  "Rangeen",
  "Earthen Oven - Fortune Landmark",
  "Zodiac- Fortune Landmark",
  "The Square - Hotel Novotel",
  "Collage - Hyatt",
  "Timpani - Radisson Blu",
  "MoMo Café - Courtyard By Marriott",
  "Tabebuia - Glade One",
  "Narmada - The Ummed",
  "The Eatery - Four Points by Sheraton",
  "The Great Kabab Factory - Radisson Blu",
  "Wind & Water- Fortune Landmark",
  "Jacaranda - The Ummed",
  "Gardenia - Fortune Park",
  "Citrus Cafe - Lemon Tree Premier",
  "Dum ka Zaika- Narayani Heights",
  "Dot Yum - Hotel Aloft",
  "Biergarten",
  "TBC Sky Lounge",
  "TBC- Sky Lounge",
  "The Big Barbeque",
  "Barbeque Nation",
  "Barbecue by Punjab Grill",
  "AB's - Absolute Barbecues",
  "UDP Urban Deccan Pub",
  "Byg Brewski Brewing Company",
  "Brahma Brews",
  "Communiti",
  "Street Storyss",
  "Stories - The Brew Chapter",
  "The Black Pearl",
  "The Globe Grub",
  "The Terrace at Gilly's Redefined",
  "Chili's American Grill & Bar",
  "Mainland China",
  "The Big Barbeque",
  "The Pallet",
  "Burma Burma",
  "The Black Pearl",
  "Pasta Street",
  "Stories",
  "Tipsy Bull - The Bar Exchange",
  "ANTIGRAVITY",
  "Fire Station",
  "Santé Spa Cuisine",
  "Nando's",
  "Asia Kitchen By Mainland China",
  "AB's - Absolute Barbecue",
  "Truffles",
  "Masala Mandi",
  "Xochi Bar And Kitchen",
  "The Bangalore Cafe",
  "Aurum Brew Works",
  "1131 Bar + Kitchen",
  "Empire Restaurant",
  "ShakesBierre",
  "Brewklyn Microbrewery",
  "Levitate Brewery and Kitchen",
  "China Bistro",
  "Gilly's Restobar",
  "High Drate",
  "Tipsy Bull- The Bar Exchange",
  "Chulha Chauki Da Dhaba",
  "Stories",
  "Hard Rock Cafe",
  "Gilly's Restobar",
  "Raahi",
  "Chulha Chauki Da Dhaba",
  "Pasta Street",
  "Smoke House Deli",
  "Sotally Tober",
  "Sidewalk - The Garden Bar",
  "Toscano - Mojito Bar",
  "Echoes Koramangala",
  "Fenny's Lounge And Kitchen",
  "Buff Buffet Buff",
  "Chili's American Grill & Bar",
  "Deja Vu Buffet Bar",
  "Roots",
  "Sriracha Robata & Contemporary Pan Asian Dining",
  "Sattvam",
  "Chianti",
  "Kapoor's Cafe",
  "Grill Daddy",
  "Stegi - Modern Indian",
  "The Bier Library",
  "Sotally Tober",
  "Meghana Foods",
  "Flechazo",
  "The Reservoire",
  "Inntense Restobar",
  "Simon Says Brew Works",
  "Bombay Adda",
  "La Casa Brewery And Kitchen",
  "The London Curry House - The Royale Senate Hotel",
  "Chullah Bhatti Grand",
  "Taaza Thindi",
  "Namaste",
  "Brahmin's Coffee Bar",
  "Arogya Ahaara",
  "CTR",
  "Bengaluru Cafe",
  "Namma SLN",
  "Onesta",
  "Dilli to Dakshin",
  "Veena Stores",
  "Mavalli Tiffin Room (MTR)",
  "Chikkanna Tiffin Room",
  "Malleshwaram Dosa Corner",
  "Asha Tiffins",
  "Puliyogare Point",
  "California Burrito",
  "Mumbai Tiffin",
  "HOMMS",
  "Kaapi Katte",
  "S N Refreshments",
  "Rolls & Bowls",
  "Sri Raghavendra Stores",
  "Raghavendra Tiffin",
  "Siddiqu Kabab Center",
  "Ashok Vatika",
  "IDC Kitchen",
  "Sendhoor Coffee",
  "Poha On Wheels",
  "Al Amanah Cafe",
  "Vidyarthi Bhavan",
  "Leon Grill",
  "Leon Grill",
  "Khawa Karpo",
  "Podi Idly",
  "Mooch Marod",
  "Hari Super Sandwich",
  "Just Shawarma",
  "Manjit Da Dhaba",
  "Aattutheeram Kerala Restaurant",
  "Hotel Aditya",
  "Mavalli Tiffin Room (MTR)",
  "By 2 Coffee",
  "South Kitchen",
  "eat.fit Cafe",
  "Gods Own Cafe",
  "Habibi Falafel",
  "The Bundle Co.",
  "Mooch Marod - Non Veg",
  "Cravy Wings",
  "Real Fresh Dosa Corner",
  "Deccan Paradise",
  "Brahmins' Thatte Idli",
  "Hotel Dwarka",
  "Sri Laxmi Venkateshwara Coffee Bar",
  "Popular Burger",
  "Om Sai Skanda Dosa Camp",
  "Mane Holige",
  "Kurtosshhh",
  "Bharat Bistro",
  "HVR Veg",
  "Gavran Misal",
  "Udupi Grand",
  "Dhuaan",
  "Sri Krishna Upahara",
  "Kanti Sweets",
  "Juicy",
  "Dose Manjanna",
  "Maruthi Davangere Benne Dosa",
  "Chaatimes",
  "Shivaji Military Hotel",
  "Ayodhya Upachar",
  "Kota Kachori",
  "Shree Muthahalli Veg",
  "eat.fit",
  "Ranganna Military Hotel",
  "Shuddh Desi Khana",
  "The Filter Coffee",
  "Halli Jonne Biriyani",
  "Eat Street",
  "MTR 1924",
  "Anand Sweets And Savouries",
  "Ambur Biryani Point",
  "Tibetan Kitchen",
  "Purani Dilli By Anand Sweets",
  "O.G. Variar & Sons",
  "Happy Belly Bakes",
  "The Deli - The Den Bengaluru",
  "Amintiri",
  "Magnolia Bakery",
  "Glen's Bakehouse",
  "Cakewala",
  "Albert Bakery",
  "Breads and Banter",
  "The Sugar Fairy",
  "Soul Treat",
  "Cake Zone",
  "Aubree",
  "Cafe Del Sol",
  "Cakesta",
  "V B Bakery",
  "Marzipan Cafe & Bakery",
  "Kreme Delight",
  "The Bakers Table",
  "Patisserie Nitash",
  "WarmOven Cake & Desserts",
  "The Humble Pie",
  "Happy Endings",
  "Cupcake Noggins",
  "Bake Ur Wish",
  "Occasions",
  "Thom's Bakery",
  "Redberrys",
  "Chantilly",
  "Cafe Arabica",
  "Amma's Pastries",
  "Magic Oven",
  "Chocoberry",
  "The Bangalore Bakery",
  "Bread Crumbs Bakery",
  "Floured-Baked With Love",
  "Happy Belly Bakes",
  "Lagom Patisserie",
  "The Ganache Factory",
  "Chef Baker's",
  "Skyline Pizzeria",
  "Happy Belly Bakes",
  "Grubshack",
  "Just Bake",
  "Lemon Krust",
  "Bakers Abode",
  "Creme Bliss",
  "The Rolling Pin",
  "ibaco",
  "Bun World",
  "Cookie Man",
  "Bakingo",
  "Frosted Memories",
  "Karachi Bakery",
  "Bake Addiction",
  "Cottage Loaf",
  "The Humble Pie",
  "Sweet Truth",
  "Maiyas",
  "Baker's Home",
  "CNS Pastries",
  "Cake Cafe",
  "Karachi Bakery",
  "Sweet Chariot",
  "Cake Town Cafe",
  "Cremee",
  "Atty's Bakery",
  "Bakers Day",
  "Burger Yard",
  "The Hole In The Wall Cafe",
  "Brik Oven",
  "Kurtoskalacs",
  "Nuage",
  "Lavonne",
  "Truffles",
  "Smoor",
  "Bloomsbury's Global Kitchen & Bakehouse",
  "Stoner",
  "Mudpipe Cafe",
  "Go Native",
  "Onesta",
  "Chai Days",
  "The Blue Wagon - Kitchen",
  "Burger Seigneur",
  "Onesta",
  "Dyu Art Cafe",
  "The Hobbit Cafe",
  "A Hole Lotta Love Cafe",
  "Loft",
  "Tea Villa Cafe",
  "Here & Now",
  "Foxtrot - House of Subculture",
  "Stoner",
  "Third Wave Coffee Roasters",
  "Market Table",
  "Café Kaffea",
  "Bamboo Hut",
  "Hillstation Cafe",
  "Japan Travel Cafe Azuki",
  "Springold - The Luxury Cafe",
  "Hungry Hippie",
  "Cafe Azzure",
  "Skoolroom",
  "Lazy Suzy",
  "Enerjuvate Studio & Cafe",
  "YORK St.",
  "Smoor",
  "Based On A True Story- Bistro",
  "Dolci Desserts",
  "Cafe Max",
  "Matteo Coffea",
  "Justbe Resto Cafe",
  "Cafe Medley",
  "Infinitea Tea Room & Tea Store",
  "Peppa Zzing",
  "Starbucks Coffee",
  "Chai Galli",
  "Shake It Off",
  "99 Pancakes",
  "Blue Tokai Coffee Roasters",
  "Flax",
  "Bistro Bois",
  "Fabcafe",
  "The Roastery",
  "Eating Love",
  "Third Wave Coffee Roasters",
  "Pure & Sure Organic Cafe",
  "Chaayos",
  "Dice N Dine",
  "Green Theory",
  "Le Terrace Café",
  "Tea Villa Cafe",
  "Alchemy Coffee Roasters",
  "Skytouch Le Cafe",
  "TAB - Take A Break",
  "Tea Brew",
  "Giselle Resto Cafe",
  "Chai Galli",
  "Yauatcha",
  "Rim Naam - The Oberoi",
  "Caperberry",
  "Saffron - Radisson Blu",
  "Shao - Radisson Blu",
  "JW Kitchen - JW Marriott Bengaluru",
  "Melange - Radisson Blu",
  "Kazé",
  "Shiro",
  "Karavalli - The Gateway Hotel",
  "Alba - JW Marriott Bengaluru",
  "Spice Terrace - JW Marriott",
  "Salvadores",
  "Ssaffron - Shangri-La Hotel",
  "Masala Klub - The Taj West End",
  "Café 77 East - Taj Bangalore",
  "Bo Tai",
  "Grasshopper",
  "Cubbon Pavilion - ITC Gardenia",
  "Feast - Sheraton Grand Bangalore Hotel at Brigade Gateway",
  "Feast - Sheraton Grand Bengaluru Whitefield Hotel & Convention Centre",
  "Blue Ginger - The Taj West End",
  "The Lantern Restaurant & Bar - The Ritz-Carlton, Bangalore",
  "Memories of China - Taj MG Road Bengaluru",
  "Royal Afghan - ITC Windsor",
  "Kebabs & Kurries - ITC Gardenia",
  "Edo Restaurant & Bar - ITC Gardenia",
  "Caprese - Shangri-La Hotel",
  "Tiamo - Conrad Bengaluru",
  "Ottimo - ITC Gardenia",
  "Le Cirque Signature - The Leela Palace",
  "Tijouri - Radisson Blu Atria",
  "M Cafe - Bengaluru Marriott Hotel Whitefield",
  "Citrus - The Leela Palace",
  "Jamavar - The Leela Palace",
  "b Café - Shangri-La Hotel",
  "The Persian Terrace - Sheraton Grand Bangalore Hotel at Brigade Gateway",
  "Ministry of Food - Hilton Bangalore Embassy GolfLinks",
  "Blue Terrain - Novotel",
  "The Square - Novotel",
  "The Raj Pavilion - ITC Windsor",
  "The Market - The Ritz-Carlton",
  "Tiger Trail - Royal Orchid Hotel",
  "Shang Palace - Shangri-La Hotel",
  "Caraway Kitchen - Conrad Bengaluru",
  "Dum Pukht Jolly Nabobs - ITC Windsor",
  "Alto Vino - Bengaluru Marriott Hotel Whitefield",
  "Lotus Pavilion - ITC Gardenia",
  "Dakshin - ITC Windsor",
  "Mikusu - Conrad Bengaluru",
  "Yataii - Shangri-La Hotel",
  "Whitefield Bar and Grill - Bengaluru Marriott Hotel Whitefield",
  "CUR8 - Four Seasons Hotel",
  "Indian Durbar - Conrad Bengaluru",
  "Mynt - The Taj West End",
  "12th Main - Grand Mercure",
  "Asia Alive - DoubleTree Suites By Hilton",
  "24@43 - The Oterra",
  "Bene - Sheraton Grand Bangalore Hotel at Brigade Gateway",
  "Riwaz - The Ritz-Carlton",
  "Zen - The Leela Palace",
  "The Hebbal Cafe - Courtyard By Marriott",
  "OKO - The Lalit Ashok Bangalore",
  "WelcomCafe Jacaranda - WelcomHotel Bengaluru",
  "The Salt Grill - Hilton Bangalore Embassy Golflinks",
  "Polo Club - The Oberoi",
  "GYLT",
  "Tamarind - Taj Bangalore",
  "Limelight - Royal Orchid Hotel",
  "Kava - Fairfield by Marriott",
  "Citrus Cafe - Lemon Tree Hotel",
  "Latitude Whitefield",
  "Monsoon - The Park Bangalore",
  "Terracotta Whitefield",
  "Azure - Taj Yeshwantpur",
  "Baluchi - The Lalit Ashok Bangalore",
  "Alloro - The Oterra",
  "Incanto - The Zuri",
  "East- The Oterra",
  "Soi & Sake - Taj Bangalore",
  "Tandoor",
  "24/7 - The Lalit Ashok Bangalore",
  "Ithaca - The Chancery Pavilion",
  "Italia - The Park Bangalore",
  "Fish Factory-Citrus Hotel",
  "Soul Indian Specialty - Svenska Design Hotel",
  "M Bar - Bengaluru Marriott Hotel Whitefield",
  "Infinity - The Zuri",
  "Tiffin Room - Miraya Hotel & Residences",
  "BBCUE Whitefield",
  "Merak-JW Marriott Hotel",
  "Rumbah",
  "Chili's",
  "Nando's",
  "Hall Gate",
  "The G.T. Road",
  "Barbeque Nation",
  "Pirates Of Grill",
  "United Coffee House Rewind",
  "Dhaba Estd. 1986 Delhi",
  "Parcel",
  "Boathouse",
  "Qizo",
  "Brooklyn Central",
  "Baithak",
  "The Finch",
  "Attic",
  "Dastaan",
  "Lamhe",
  "City Buzz Reloaded",
  "Bisaat",
  "Biryani By Kilo",
  "CAFÈ JC's",
  "World Food Centre",
  "Boston Bites",
  "Backpackers Cafe",
  "The Barbeque Paradise",
  "Mr. Singh's Kitchen",
  "Farzi Cafe",
  "AJA Fresh, Grilled & Healthy",
  "Biryani By Kilo",
  "Swagath Restaurant & Bar",
  "Tossin Pizza",
  "Noorani By Nihari",
  "Kylin Experience",
  "The Reef",
  "Brew Bros",
  "Hunka Hunka Town",
  "Playground",
  "Cottage",
  "City Cabana",
  "Xtreme Sports Bar & Grill",
  "Dak Bunglow",
  "FourFolks",
  "Molecule Air Bar",
  "JnJ's",
  "Sagar Ratna",
  "Mainland China",
  "Casa Bella Vista Pizzeria",
  "The Willow Cafe",
  "Boston Bites",
  "Puzzles",
  "The Romeo's Locale",
  "Rebelle Bar & Kitchen",
  "JB's Kitchen",
  "The Great Kabab Factory",
  "Wasabi",
  "Dialogue Cafe",
  "Sundarams",
  "The Green Emerald - Forest Hill Golf & Country Club",
  "Cafe G - Holiday Inn",
  "Biryani Art",
  "Katani Dhaba",
  "Khalsa Dhaba",
  "Baba Dairy",
  "Garam Dharam",
  "The Escape",
  "Rustic Door",
  "Culture Brew Exchange",
  "Char-B-Que 100% Veg",
  "The Horseshoe Bar Exchange",
  "Chandiland",
  "Tamzaraa Kafe & Club",
  "Ministry of Bar Exchange",
  "Benares",
  "Swagath Restaurant & Bar",
  "Faraabi Cafe",
  "Sky Mansion",
  "Adda Microbrewery",
  "Patio Terrasse - Golden Tulip",
  "Aqua Blue",
  "Tattlers",
  "Fabcafe",
  "The Kronks",
  "Petu Pankaj",
  "Dryp",
  "Yo! China",
  "Lezzetli",
  "Karim's Delhi 6",
  "Pradhan Dhaba",
  "Chokhi Dhani",
  "The Brewmaster - Arista Hotel",
  "Masala Grill",
  "Urban Thikana",
  "PunChin",
  "SHANGZ",
  "Subway",
  "Milkshake and Co.",
  "Uncle Jack's",
  "Bhathal Rasoi",
  "Barneys",
  "Super Donuts- American Eatery & Bakery",
  "Ram Dairy",
  "Chilli 65",
  "Transform Diet",
  "UFO Fries & Corn",
  "Wat-a-Burger",
  "Swag",
  "The Pizza Story",
  "La Pino'z Pizza",
  "Karthik",
  "Burgrill",
  "Preet Eating Zone",
  "The London Shakes",
  "Ram Chat Bhandar",
  "KFC",
  "Ghar Ka Khaana",
  "Freshlane & Co.",
  "Charcoal Eats",
  "SuperYum",
  "Gopal Ji Confectioners",
  "Food@U",
  "McDonald's",
  "Taco Bell",
  "Avin Karthik",
  "Chick Blast",
  "Burger Hub",
  "Haramrit Vaishno Dhaba",
  "Castle Grill",
  "Lazeez Rasoi",
  "Chilli Chaats",
  "Awadhi Central",
  "Hot Feast",
  "Va Sano",
  "Foody Hub",
  "Tucker's House",
  "B. K. Confectionery",
  "Michigan Pizza Company",
  "Special Amritsari Kulcha",
  "Daddy Waffle",
  "New York Masala",
  "European Bite",
  "Naman Pizzeria & Barbecue",
  "Nugget Nation",
  "Curry N Spices",
  "Himalayan Food Plaza",
  "Road Side Bells...",
];